#!/bin/bash

set -e

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${local_sha}" = $z40 ]]; then
    echo "Deleting stuff, nothing to do"
else
    poetry install
    poetry run invoke lint
    poetry run pytest
  fi
done

exit 0
