#!/bin/bash

set -e

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${local_sha}" = $z40 ]]; then
    echo "Deleting stuff, nothing to do"
  else
    skyspell-ci run
    (
      cd python
      poetry install
      poetry run invoke lint
    )
    (
      cd tests
      poetry install
      poetry run invoke lint
    )
    (
      cd java
      ./mvnw test
    )
    (
      cd javascript
      yarn
      yarn lint
      yarn test
    )
    (
      cd infra/stress-test/
      cargo clippy
    )
  fi
done

exit 0
