# Generated by Django 3.2.9 on 2021-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField()),
                ("city", models.TextField()),
                ("zip_code", models.TextField()),
                ("email", models.TextField()),
            ],
        ),
    ]
