# Generated by Django 3.2.9 on 2021-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_auto_20211102_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
