# Generated by Django 3.2.9 on 2021-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address_line2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
