# Generated by Django 3.2.9 on 2021-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_auto_20211102_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address_line2",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
