# Generated by Django 3.2.10 on 2021-12-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_alter_employee_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address_line2",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
