# Generated by Django 3.2.10 on 2021-12-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_auto_20211229_1247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address_line2",
            field=models.CharField(max_length=100),
        ),
    ]
