# Generated by Django 3.2.10 on 2021-12-29 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_address_line2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
